apiVersion: v1
kind: Service
metadata:
  name: monitoring-frontend-service
spec:
  type: NodePort
  selector:
    app: monitoring-frontend-pod
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30032